#[derive(Clone, Debug)]
pub enum Token {
    Identifier { value: String },
    String { value: String },
    Number { value: i64 },
    FloatingPoint { value: f64 },
    Newline,
    Indent,
    Dedent,
    KeywordAnd,
    KeywordBreak,
    KeywordCase,
    KeywordClass,
    KeywordContinue,
    KeywordDefault,
    KeywordElse,
    KeywordEnum,
    KeywordFalse,
    KeywordFn,
    KeywordFor,
    KeywordFrom,
    KeywordIf,
    KeywordImport,
    KeywordIn,
    KeywordLet,
    KeywordLoop,
    KeywordMatch,
    KeywordMut,
    KeywordOr,
    KeywordPass,
    KeywordPub,
    KeywordReturn,
    KeywordStruct,
    KeywordSwitch,
    KeywordTrue,
    KeywordVar,
    KeywordWhile,
    Colon,
    DoubleColon,
    Dot,
    Arrow,
    Comma,
    Less,
    Greater,
    Equal,
    DoubleEqual,
    NotEqual,
    GreaterEqual,
    LessEqual,
    Plus,
    Minus,
    Asterix,
    Slash,
    PlusEqual,
    MinusEqual,
    ShiftRight,
    ShiftLeft,
    Pipe,
    Hat,
    Ampersand,
    OpeningParenthesis,
    ClosingParenthesis,
    OpeningBrace,
    ClosingBrace,
    OpeningBracket,
    ClosingBracket,
}
