#[derive(Clone, Debug)]
pub enum Token {
    Identifier { value: String },
    String { value: String },
    Number { value: i64 },
    FloatingPoint { value: f64 },
    Newline,
    Indent,
    Dedent,
    KeywordAnd,
    KeywordBreak,
    KeywordClass,
    KeywordContinue,
    KeywordElse,
    KeywordEnum,
    KeywordFalse,
    KeywordFn,
    KeywordFor,
    KeywordIf,
    KeywordImport,
    KeywordIn,
    KeywordLet,
    KeywordLoop,
    KeywordMatch,
    KeywordMut,
    KeywordOr,
    KeywordPass,
    KeywordPub,
    KeywordReturn,
    KeywordStruct,
    KeywordTrue,
    KeywordVar,
    KeywordWhile,
    Colon,
    DoubleColon,
    Dot,
    Arrow,
    Comma,
    Less,
    Greater,
    Equal,
    DoubleEqual,
    NotEqual,
    GreaterEqual,
    LessEqual,
    Plus,
    Minus,
    Asterix,
    Slash,
    OpeningParenthesis,
    ClosingParenthesis,
    OpeningBrace,
    ClosingBrace,
}

#[derive(Clone, Debug, Default)]
pub struct Location {
    pub row: i32,
    pub column: i32,
}
