name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-python-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'black>=20'
      - name: Run black formatting checker
        run: python -m black compiler1 --check

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r compiler1/requirements.txt
      - name: Test with pytest
        run: pytest test_compiler1.py -v
      - name: Bootstrap
        run: bash bootstrap2.sh
      - name: Build all
        run: make
      - name: Check slang unit tests
        run: make check

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r compiler1/requirements.txt
      - name: Test with pytest
        run: pytest test_compiler1.py -v
