name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r compiler1/requirements.txt
      - name: Test with pytest
        run: pytest test_compiler1.py -v
      - name: Bootstrap
        run: bash bootstrap2.sh
      - name: Check slang unit tests
        run: make check
